jwt:
  key: ${SECRECT_KEY}

spring:
  application:
    name: XStore
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com/
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash